import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>frogTech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col justify-center mb-10'>
        <h1 className="text-6xl flex gap-3 flex-wrap items-center justify-center my-5">
          frogTech
          <Image height={90} width={90} alt="frog" src="/frog.png" />
        </h1>
        <div className='flex md:px-40 flex-wrap justify-center w-full gap-4'>
          <div className='border-2 border-opacity-90 border-neutral-900 rounded-md p-5 max-w-[250px] hover:border-[#003233]  duration-700'>

            <Link href="https://poking.frogtech.dev">
              <h2 className='text-3xl'>POKING &rarr;</h2>
            </Link>

            <p className='text-1xl'>Do POKING, be the second or third to listen to a soon to be popular song</p>
            <Link href="https://github.com/fr0gtech/spoty-stalk">
              <div className="bg-neutral-900 p-2 rounded mt-3 duration-500 !text-white opacity-40 hover:opacity-95">
                <p className='!text-sm !mt-1 font-semibold'>spoty-stalk - by frogtech</p>
                <p className='!text-sm !my-1'>stalk someones public spotify playlists </p>
              </div>
            </Link>
          </div>
          <div className='border-2 border-opacity-90 border-neutral-900 rounded-md p-5 max-w-[250px] hover:border-[#003233]  duration-700'>
            <Link href="https://poking.frogtech.dev">
              <h2 className='text-3xl'>More Soon &rarr;</h2>
            </Link>
            <p className='text-1xl'>Join the most elite frogs</p>
            <p className='opacity-50'>if ur not a bot join discord: <code className="bg-neutral-900 text-xs p-[2px] rounded">uggcf://qvfpbeq.tt/ac5eUPEXg2</code></p>
          </div>
        </div>
      </main>
      <footer className='text-center'>
          FrogTech &copy; {new Date().getFullYear()}
      </footer>
    </div>
  )
}
