import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Github from "../public/github.svg"

const ArticleComp = dynamic(() => import('../components/article'), {
  ssr: false,
})
export default function Home() {
  return (
    <div className='container mx-auto flex flex-col min-h-screen'>
      <Head>
        <title>frogTech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col grow'>
        <h1 className="text-5xl flex gap-3 flex-wrap items-center justify-center my-5">
          frogTech
          <Image height={90} width={90} alt="frog" src="/frog.png" className=' brightness-200' />
        </h1>
        <div className=' flex md:px-40 flex-wrap justify-center w-full gap-4'>
          <ArticleComp
            color="cyan-500"
            link="https://poking.frogtech.dev"
            title="POKING"
            text="Do POKING, be the second or third to listen to a soon to be popular song"
            cta={{
              title: "spoty-stalk - by frogtech",
              text: "stalk someones public spotify playlists",
              link: "https://github.com/fr0gtech/spoty-stalk"
            }}
            tags={[
              { name: 'app', color: 'bg-cyan-500' },
              { name: 'open source', color: 'bg-purple-500' },
              { name: 'spotify', color: 'bg-[#1DB954]' }

            ]}
          />
          <ArticleComp
            color="blue-500"
            link="#"
            title="More Soon"
            text="Join the most e1337 frogs, build the future!"
            cta={{
              title: "if not bot: joinDiscord()",
              text: <code className="bg-neutral-900 text-xs p-[2px] rounded">uggcf://qvfpbeq.tt/ac5eUPEXg2</code>,
              link: "uggcf://qvfpbeq.tt/ac5eUPEXg2"}}
            />
        </div>
      </main>
    </div>
  )
}
